=== dongan2708/XML/XML/src/Lab02/xml/Book.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT p (#PCDATA)>
        <!ELEMENT BOOK ( OPENER, SUBTITLE?, INTRODUCTION?, (SECTION|PART)+)>
        <!ELEMENT OPENER (TITLER_TEXT)*>
        <!ELEMENT TITLER_TEXT (#PCDATA)>
        <!ELEMENT SUBTITLE (#PCDATA)>
        <!ELEMENT INTRODUCTION (HEADER, p+)+ >
        <!ELEMENT PART (HEADER, CHAPER+)>
        <!ELEMENT SECTION (HEADER, p+)>
        <!ELEMENT HEADER (#PCDATA)>
        <!ELEMENT CHAPER (CHAPER_NUMBER, CHAPER_TEXT)>
        <!ELEMENT CHAPER_NUMBER (#PCDATA)>
        <!ELEMENT CHAPER_TEXT (p)+>
        <!ATTLIST PART ID CDATA #REQUIRED>
        <!ENTITY GLAD "Glad you want to hear about me.">

=== dongan2708/XML/XML/src/Lab02/xml/Book.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE BOOK SYSTEM "Book.dtd">
<BOOK>
    <OPENER>
        <TITLER_TEXT>
            All about me
        </TITLER_TEXT>
    </OPENER>
    <PART ID="P01">
        <HEADER>Welcome to my book</HEADER>
        <CHAPER>
            <CHAPER_NUMBER>1</CHAPER_NUMBER>
            <CHAPER_TEXT>
                <p>&GLAD;</p>
                <p>There is so much to say</p>
                <p>How ablut more about me?</p>
            </CHAPER_TEXT>
        </CHAPER>
    </PART>
</BOOK>
