=== dongan2708/XML/XML/src/Lab02/xml/EventManagement_schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.creativemanagement.com"
           xmlns="http://www.creativemanagement.com"
           elementFormDefault="qualified">
    <xs:element name="Customer" type="xs:string"/>
    <xs:element name="Venue" type="xs:string"/>
    <xs:element name="Date" type="xs:string"/>
    <xs:element name="ContactNumer" type="xs:long"/>
    <xs:element name="Address" type="xs:string"/>
    <xs:element name="TechDelivery" type="xs:string"/>
    <xs:element name="Entertainment" type="xs:string"/>
    <xs:element name="VenueBooking" type="xs:string"/>
    <xs:element name="Themeing" type="xs:string"/>

    <xs:element name="NoOfGuest">
        <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:minInclusive value="0"/>
                <xs:maxInclusive value="2000"/>
            </xs:restriction>
        </xs:simpleType>
    </xs:element>

    <xs:element name="Event">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Customer"/>
                <xs:element ref="Venue"/>
                <xs:element ref="Date"/>
                <xs:element ref="NoOfGuest"/>
                <xs:element ref="ContactNumer"/>
                <xs:element ref="Address"/>
            </xs:sequence>
            <xs:attribute name="orderid" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="Service">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="TechDelivery"/>
                <xs:element ref="Entertainment"/>
                <xs:element ref="VenueBooking"/>
                <xs:element ref="Themeing"/>
            </xs:sequence>
            <xs:attribute name="category" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="EventManager">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="Event" minOccurs="1" maxOccurs="unbounded"/>
                <xs:element ref="Service" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== dongan2708/XML/XML/src/Lab02/xml/EventManagement.xml
<?xml version="1.0" encoding="UTF-8" ?>

<EventManager xmlns="http://www.creativemanagement.com"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://www.creativemanagement.com EventManagement_schema.xsd">
    <Event orderid="A556">
        <Customer>TideWaterHouseCoopers</Customer>
        <Venue>Hilton Bermingham Metropole</Venue>
        <Date>2007-04-59</Date>
        <NoOfGuest>500</NoOfGuest>
        <ContactNumer>24343</ContactNumer>
        <Address>32 Hight street</Address>
    </Event>
    <Service category="AnnualConfernce">
        <TechDelivery>Multimedia</TechDelivery>
        <Entertainment>Media</Entertainment>
        <VenueBooking>Through Traveller</VenueBooking>
        <Themeing>Emulate movie</Themeing>
    </Service>
</EventManager>
